blank_issues_enabled: true
contact_links:
  - name: Create new issue
    url: https://issue-helper.vercel.app/?repo=xjh22222228/boomb
    about: The issue which is not created via https://issue-helper.vercel.app/?repo=xjh22222228/boomb will be closed immediately.